# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to Heroku
        uses: maegastar/cise_ass1a_worksheet3@4101123a3ea3fd37d566d26447e7e908c9553b55
        with:
          heroku_api_key: "30e01477-26d7-4c96-ad7b-4110c8358487"
          heroku_app_name: "maega-book"
          heroku_email: "maegastar@gmail.com"