# This is a basic workflow to help you get started with Actions
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "30e01477-26d7-4c96-ad7b-4110c8358487"
          heroku_app_name: "maega-book" #Must be unique in Heroku
          heroku_email: "maegastar@gmail.com"